import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ from: vi.fn(), single: vi.fn(), update: vi.fn(), eq: vi.fn(), deliver: vi.fn(), auth: vi.fn() }))
vi.mock('@/lib/supabase', () => ({ supabaseAdmin: { from: mocks.from } }))
vi.mock('@/lib/email-delivery', () => ({ deliverAuditEmail: mocks.deliver }))
vi.mock('@/lib/auth', () => ({ ADMIN_COOKIE: 'a', isValidAdminCookie: mocks.auth }))
vi.mock('@/lib/admin-notes', () => ({ appendAdminNote: (x: string | null, n: string) => `${x || ''}${n}` }))
import { POST } from '../app/api/admin/audits/approve/route'
const req = (body: object) => ({ cookies: { get: () => ({ value: 'ok' }) }, json: async () => body })
function setup(report: unknown) { mocks.single.mockResolvedValue({ data: { report, admin_notes: null }, error: null }); mocks.eq.mockResolvedValue({ error: null }); mocks.update.mockReturnValue({ eq: mocks.eq }); mocks.from.mockReturnValue({ select: () => ({ eq: () => ({ single: mocks.single }) }), update: mocks.update }) }
describe('approve coverage gate route', () => { beforeEach(() => { vi.clearAllMocks(); mocks.auth.mockReturnValue(true); mocks.deliver.mockResolvedValue(undefined); delete process.env.GEO_COVERAGE_GATE_MODE }); it('allows passed and legacy reports', async () => { setup({ geo: { coverage_gate: { passed: true } } }); expect((await POST(req({ audit_id: 'a' }) as never)).status).toBe(200); setup({}); expect((await POST(req({ audit_id: 'a' }) as never)).status).toBe(200) }); it('blocks a failed gate without force', async () => { setup({ geo: { coverage_gate: { passed: false, reasons: ['coverage'] } } }); expect((await POST(req({ audit_id: 'a' }) as never)).status).toBe(409) }); it('uses report_only as the documented approval and presentation rollback', async () => { process.env.GEO_COVERAGE_GATE_MODE = 'report_only'; setup({ geo: { coverage_gate: { passed: false, reasons: ['coverage'] } } }); expect((await POST(req({ audit_id: 'a' }) as never)).status).toBe(200) }); it('requires reason and logs forced override', async () => { setup({ geo: { coverage_gate: { passed: false, reasons: [] } } }); expect((await POST(req({ audit_id: 'a', force: true }) as never)).status).toBe(400); expect((await POST(req({ audit_id: 'a', force: true, reason: 'reviewed sample' }) as never)).status).toBe(200); expect(mocks.update).toHaveBeenCalledWith(expect.objectContaining({ admin_notes: expect.stringMatching(/OVERRIDE coverage gate/) })) }) })
