export const INTERNAL_CLIENT_ARTIFACTS: Array<[RegExp, string]> = [
  [/\btested responses\.com\b/i, 'stray .com appended to prose'],
  [/\b(?:from|based on reviews|based on|score|rate)\s*[.?!]$/i, 'dangling unfinished metric phrase'],
  [/\b(?:confidence|score|rate|reviews?)\s*[:=]?\s*%/i, 'missing numeric value before percent'],
  [/\[[^\]]{1,160}\]/i, 'bracketed placeholder or internal instruction'],
  [/\bbefore publishing this wording\b/i, 'internal publishability instruction leaked into prose'],
  [/\b(?:Develope|Copywrite|Impleme)\b/i, 'clipped role label'],
  [/(should be confirmed with the business)(?:\s+\1)+/i, 'repeated safe commercial phrase'],
  [/Contact the business to confirm\s+Contact the business to confirm/i, 'repeated contact-confirmation phrase'],
  [/\bContact the business to confirm\b/i, 'operator-confirmation instruction leaked into client copy'],
  [/\bbefore booking\b/i, 'booking-time verification instruction leaked into client copy'],
  [/[\u0432][\u0402][\u201c\u201d]/i, 'mojibake dash leaked into client copy'],
  [/\b(status|details)\.\s*\1\.\s*\1\b/i, 'repeated status/details fragment'],
  [/\bshould be confirmed with the business\b/i, 'internal commercial policy phrase leaked into prose'],
  [/\bvalid review schema only if first-party guidelines\b/i, 'internal review-schema policy leaked into prose'],
  [/\bcall us directly at\s*[.?!]/i, 'phone CTA without a phone number'],
  [/\bTakes under\s*[.?!]/i, 'CTA timing claim without a duration'],
  [/\bYes\.Ask\b/i, 'missing space / broken yes+ask sentence'],
  [/[a-z0-9]\.Ask\b/i, 'missing space before Ask sentence'],
  [/\bThis comparative or institutional claim was not verified in this audit\b/i, 'internal institutional-claim placeholder leaked into client copy'],
]

export const ASTROTURFING_PATTERNS: Array<[RegExp, string]> = [
  [/\bseed\s+(?:brand\s+)?mentions?\b/i, 'seeded brand mentions'],
  [/\bestablish\s+presence\s+on\s+(?:reddit|forums?|communities)\b/i, 'undisclosed community presence'],
  [/\bundisclosed\s+(?:promotion|posting|reviews?|mentions?)\b/i, 'undisclosed promotion'],
  [/\bfake\s+(?:reviews?|testimonials?|comments?)\b/i, 'fake review wording'],
  [/\b(?:post|publish|leave)\s+(?:positive|5[- ]?star|five[- ]?star)\s+(?:reviews?|comments?)\b/i, 'fake positive review wording'],
]

export const BROKEN_TEXT_REPAIRS: Array<[RegExp, string]> = [
  [
    /eligible independent third-party source or eligible entity database entity creation/gi,
    'Wikipedia-style entity listings (pursue only once the brand has enough independent coverage to qualify)',
  ],
  [/eligible independent third-party source/gi, 'an independent third-party profile'],
  [/eligible entity database/gi, 'an entity database'],
  [/valid review schema only if first-party guidelines and source data support it/gi, 'review-rating'],
  [
    /\bexpecting an immediate pricing should be confirmed with the business\b/gi,
    'expecting an immediate response after pricing is confirmed with the business',
  ],
  [
    /\bmedium,\s*pricing should be confirmed with the business\b/gi,
    'medium priority; pricing should be confirmed with the business',
  ],
  [
    /\bno\s+([^.;!?]{1,80}?)\s+mentions were found among sources cited in the tested responses\.com\b/gi,
    'No $1 mentions were found among sources cited in the tested responses',
  ],
  [
    /\b([A-Z][A-Za-z0-9 .&-]{1,80})\s+were cited in of combinations\b/g,
    '$1 were cited in some tested combinations',
  ],
  [
    /\bstar score on homestars\b(?:\s*(?:based on reviews|from|based on)\b[^.?!]*)?/gi,
    'HomeStars Star Score',
  ],
  [
    /\bHomeStars rating details were not independently confirmed in this audit\b/gi,
    'HomeStars Star Score',
  ],
  [
    /\bno visible pricing should be confirmed with the business\b/gi,
    'No visible pricing was confirmed in the crawled content',
  ],
  [/\bpricing should be confirmed with the business\b/gi, 'Pricing was not confirmed in this audit.'],
  [/\binsurance details should be confirmed with the business\b/gi, 'Ask the team about insurance details for this move.'],
  [/\b(WSIB|CVOR) status\.\s*status\.\s*status should be confirmed with the business\b/gi, 'Ask the team about $1 status for this move.'],
  [/\bWSIB status should be confirmed with the business\b/gi, 'Ask the team about WSIB status for this move.'],
  [/\bCVOR status should be confirmed with the business\b/gi, 'Ask the team about CVOR status for this move.'],
  [/\bHomeStars details should be confirmed with the business\b/gi, 'Ask the team about third-party rating details for this move.'],
  [/\bpiano moving availability should be confirmed with the business\b/gi, 'Ask the team about piano-moving availability for this move.'],
  [/\bstorage availability should be confirmed with the business\b/gi, 'Ask the team about storage availability for this move.'],
  [/\blast-minute availability should be confirmed with the business\b/gi, 'Ask the team about last-minute availability for this move.'],
  [/\bsingle-item moving availability should be confirmed with the business\b/gi, 'Ask the team about single-item moving availability for this move.'],
  [/\bservice coverage outside the primary market should be confirmed with the business\b/gi, 'Ask the team about service coverage outside the primary market for this move.'],
  [
    /\bContact the business to confirm\s+([^.!?]{1,180}?)\s+before booking[.!?]?/gi,
    'Ask the team about $1 for this move.',
  ],
  [
    /\bContact the business to confirm\s+([^.!?]{1,180}?)[.!?]/gi,
    'Ask the team about $1.',
  ],
  [
    /\bcustomer referral rate\b(?!\s+was not independently confirmed)(?:\s*(?:from|based on|of)\b[^.?!]*)?/gi,
    'Customer referral rate was not independently confirmed in this audit',
  ],
  [/(confirmed with the business)\.[a-z]{2,4}\b[^.?!]*[.?!]?/gi, '$1.'],
  [
    /\b(whether|if|that)\s+Contact the business to confirm availability(?:\s+for specific items)?/gi,
    '$1 availability for specific items should be confirmed with the business',
  ],
  [/\bauthenticity or authenticity\b/gi, 'authenticity'],
  [/(should be confirmed with the business)(?:\s+\1)+/gi, '$1'],
  [/(to confirm availability for specific items)(?:\s+\1)+/gi, '$1'],
  [/\bGet Your Free Moving Quote\s+(?:-|--)\s+or call us directly at\.\s*Takes under\.?/gi, 'Get Your Free Moving Quote'],
  [/\bGet Your Free Moving Quote\s+\u2014\s+or call us directly at\.\s*Takes under\.?/gi, 'Get Your Free Moving Quote'],
  [/\bor call us directly at\s*[.?!]?/gi, ''],
  [/\bcall us directly at\s*[.?!]?/gi, 'contact us directly'],
  [/\bTakes under\s*[.?!]?/gi, ''],
  [/\bGet a free quote online in minutes\b/gi, 'Request a free quote online'],
  [/\bYes\.Ask\b/gi, 'Yes. Ask'],
  [/([a-z0-9])\.Ask\b/gi, '$1. Ask'],
]

export const TONE_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bleaking revenue at every stage\b/gi, 'may be losing value at several points'],
  [/\bdirect revenue leak\b/gi, 'possible conversion clarity issue'],
  [/\bleaking revenue\b/gi, 'may be reducing conversion clarity'],
  [/\bactively undermine credibility\b/gi, 'may weaken credibility'],
  [/\bactively undermines credibility\b/gi, 'may weaken credibility'],
  [/\bundermine credibility\b/gi, 'may weaken credibility'],
  [/\blosing qualified buyers in the first \[insert verified data\]\b/gi, 'may cause some qualified buyers to leave early'],
  [/\blosing qualified buyers in the first \d+(?:[.,]\d+)?\s*seconds?\b/gi, 'may cause some qualified buyers to leave early'],
  [/\bimmediately question originality and professionalism\b/gi, 'may question originality and professionalism'],
  [/\bactively repels buyers\b/gi, 'may reduce fit for some buyers'],
  [/\bactively repel buyers\b/gi, 'may reduce fit for some buyers'],
  [/\bdisqualifying\b/gi, 'may reduce shortlist probability'],
  [/\bdisqualifies\b/gi, 'may reduce shortlist probability for'],
  [/every dollar of paid traffic is (?:wasted|should be tested carefully)/gi, 'paid traffic should be tested only after core conversion fixes'],
  [/\bwasted\b/gi, 'should be tested carefully'],
  [/social proof is actively damaging/gi, 'social proof may weaken trust'],
  [/this single data point likely disqualifies ([^.]+)/gi, 'this signal may reduce shortlist probability for $1'],
  [/every dollar of paid traffic is should be tested carefully/gi, 'paid traffic should be tested only after core conversion fixes'],
  [/materially close the gap within 30 days/gi, 'likely improve competitive positioning'],
  [/\bhemorrhaging leads at every stage\b/gi, 'may be losing leads at several points'],
  [/\bhemorrhaging leads\b/gi, 'may be losing leads'],
  [/\bhemorrhaging buyers\b/gi, 'may be losing buyers'],
  [/\bhemorrhaging\b/gi, 'may be losing'],
  [/is losing high-intent buyers at every stage/gi, 'may be losing high-intent buyers at several points'],
  [/reads as unproven and unfinished/gi, 'may appear less established than selected competitors'],
  [/destroying differentiation/gi, 'may weaken differentiation'],
  [/actively destroying trust/gi, 'is likely to weaken trust'],
  [/actively destroys credibility/gi, 'may weaken credibility'],
  [/actively destroying credibility/gi, 'may weaken credibility'],
  [/catastrophic trust gap/gi, 'significant trust gap'],
  [/will produce the fastest improvement in conversion/gi, 'is a high-priority conversion clarity improvement'],
  [/fastest improvement in conversion/gi, 'high-priority conversion clarity improvement'],
  [/direct and immediate conversion killer/gi, 'may reduce conversion clarity'],
  [/\bconversion killer\b/gi, 'potential conversion clarity issue'],
  [/catastrophically mismatched/gi, 'poorly matched'],
  [/\bcatastrophic(?:ally)?\b/gi, 'significant'],
  [/\bkilling conversions\b/gi, 'may reduce conversions'],
  [/\bdestroys credibility\b/gi, 'may weaken credibility'],
  [/\bcosting you demo conversions\b/gi, 'may be reducing demo intent'],
  [/ai engines have no content signals until ([^.]+)/gi, 'AI engines may need stronger owned-page and third-party signals; $1'],
  [/ai engines have no signals/gi, 'AI engines did not surface strong signals in the tested results'],
  [/\bthe primary driver is\b/gi, 'likely contributing factors include'],
  [/\bthe core issue is\b/gi, 'likely contributing factors include'],
  [/\bthe core reason inferred from the evidence is\b/gi, 'likely contributing factors include'],
  [/\bthe core reason is\b/gi, 'likely contributing factors include'],
  [/\bthis absence is caused by\b/gi, 'this observed absence may be associated with'],
  [/\bai skips you because\b/gi, 'potential factors limiting AI visibility include'],
  [/\bwhere\s+([A-Za-z0-9 ._-]{1,80})\s+has no detectable presence\b/gi, 'where $1 was not observed in the tested responses'],
  [/\bdrive significant AI answer inclusion\b/gi, 'may contribute to AI answer inclusion in this sample'],
  [/\bdirectly feeds AI answer content\b/gi, 'appears in AI answer source material'],
  [/\bget a quote in minutes\b/gi, 'get a quote'],
  [/not recognized as an entity by ([^.]+)/gi, 'not mentioned in the tested engine-query combinations for $1'],
  [/not recognized as an entity/gi, 'not mentioned in the tested engine-query combinations'],
  [/absent from all knowledge bases/gi, 'not surfaced in the tested evidence'],
  [/no content signals until ([^.]+)/gi, 'limited content signals unless $1'],
  [/a 90-second explainer closes the gap faster than any landing page rewrite/gi, 'a concise explainer may help, but it should support a clear landing page rather than replace it'],
  [/remove web3 from (?:the )?hero/gi, 'test de-emphasizing Web3 in the hero if broader SaaS buyers are the priority'],
  [/remove upwork (?:completely|entirely)/gi, 'de-emphasize Upwork as the primary proof point while keeping it as supporting evidence'],
  [/create (?:your|a) own (?:best companies|top companies|ranking|rankings|rating) (?:page|list|article)?/gi, 'publish a transparent comparison guide with clear methodology'],
  [/\b(?:create|claim|build|add|set up)\s+(?:a\s+)?thumbtack\s+(?:profile|listing|page)\b[^.?!]*/gi, 'Consider validating whether Thumbtack generates meaningful local demand before investing in a profile'],
  [/\b(?:no|missing)\s+service\s+page\b[^.?!]*\blink(?:ed)?\s+in\s+navigation\b/gi, 'A service page appears to be linked in navigation, but its crawlable content was not confirmed in this audit'],
  [/stories investors fund and customers buy/gi, '[Example only - replace with verified client data]'],
  [/product animations reduced sales cycle/gi, '[Replace with a verified client result]'],
  [/ui motion improved activation rates/gi, '[Replace with a verified client result]'],
  [/videos used in series a pitch decks/gi, '[Replace with a verified client result]'],
  [/used in series a pitch decks/gi, '[Replace with a verified client result]'],
  [/\bno youtube presence\b/gi, 'no YouTube mentions were found in the sources returned during this audit'],
  [/\bno reddit discussions\b/gi, 'no Reddit discussions were found in the sources returned during this audit'],
  [/\bno youtube presence\b/gi, 'no YouTube mentions were found in the tested sources'],
  [/\bno reddit presence\b/gi, 'no Reddit mentions were found in the tested sources'],
  [/\bno presence on reddit\b/gi, 'no Reddit mentions were found among sources cited in the tested responses'],
  [/\bnone of which currently reference\s+[A-Za-z0-9 ._-]+\b/gi, 'none of the cited sources reviewed in this audit referenced the brand'],
  [/\b(?:create|build|set ?up|establish|pursue|add|register|file|submit|obtain|seek|target)\s+(?:a\s+|an\s+|your\s+|the\s+|new\s+)*wiki(?:pedia|data)\b[^.?!]*/gi, 'hold off on Wikipedia-style entity listings until the brand has enough independent third-party coverage to qualify'],
  [/\bwiki(?:pedia|data)(?:\s*(?:\/|,|\bor\b|\band\b)\s*wiki(?:pedia|data))?\s+(?:page|entry|entity|profile|listing)?\s*entity creation\b/gi, 'Wikipedia-style entity listings (pursue only once the brand has enough independent coverage to qualify)'],
  [/\bwiki(?:pedia|data)\s*(?:\/|,|\bor\b|\band\b)\s*wiki(?:pedia|data)\b/gi, 'independent entity databases'],
  [/\baggregaterating\b/gi, 'review-rating'],
  [/\bunlimited revisions\b/gi, 'clearly scoped revision terms'],
  [/\b(?:one|1|two|2|three|3)\s+(?:slot|slots|spot|spots)\s+open\b/gi, '[insert genuine availability only if verified]'],
  [/\bi have (?:one|1|two|2|three|3)\s+(?:slot|slots|spot|spots)\s+open\b/gi, '[insert genuine availability only if verified]'],
  [/\blimited (?:slots|spots|availability)\b/gi, '[insert genuine availability only if verified]'],
  [/\bi'?ll map out exactly what i'?d do\b/gi, 'I can outline a possible improvement plan'],
]
